services:
  diplom2:
    #image: ${DOCKER_REGISTRY-}diplom2
    build:
      context: .
      dockerfile: Diplom2/Dockerfile
    environment:
        GOOGLE_APPLICATION_CREDENTIALS: "/secrets/s3/s3.json"
    user: root
    volumes:
    - C:\Users\MaRdIkUs\Downloads\diplom-457710-66215b408ef3.json:/secrets/s3/s3.json
    - "C:\\Users\\MaRdIkUs\\certs\\my-site.crt:/etc/ssl/certs/my-site.crt:ro"
    ports:
    - "8085:8080"
    - "8086:8081"
    depends_on:
    - mysql
    - qdrant
    networks:
    - mynet
    - keycloaknet
  
  migrations:
    image: migration
    build:
      dockerfile: Diplom2/migration-Dockerfile
    environment:
        GOOGLE_APPLICATION_CREDENTIALS: "/secrets/s3/s3.json"
    volumes:
    - C:\Users\MaRdIkUs\Downloads\diplom-457710-66215b408ef3.json:/secrets/s3/s3.json
    depends_on:
    - mysql
    networks:
    - mynet

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: DB1
      MYSQL_USER: DBUser
      MYSQL_PASSWORD: example1Commerce
      MYSQL_ROOT_PASSWORD: strong!1Pass
    ports:
    - "3306:3306"
    #volumes:
    #- "mysql:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 30s
      retries: 5
    networks:
    - mynet

  nginx:
    image: nginx
    ports:
    - "443:443"
    volumes:
    - "C:\\Users\\MaRdIkUs\\Diplom2\\Diplom2\\nginx.conf:/etc/nginx/conf.d/default.conf"
    - "C:\\Users\\MaRdIkUs\\Diplom2\\Diplom2\\nginx.main.conf:/etc/nginx/nginx.conf"
    - "C:\\Users\\MaRdIkUs\\certs:/etc/ssl/private"
    networks:
    - mynet
    - keycloaknet
    depends_on:
    - diplom2

  qdrant:
    image: qdrant/qdrant
    ports:
    - "6333:6333"
    - "6334:6334"
    #volumes:
    #- "C:\\Users\\MaRdIkUs\\Diplom2\\Diplom2\\qdrantstorage:/qdrant/storage:z"
    networks:
    - mynet

volumes:
  mysql:

networks:
  keycloaknet:
    external: true
  mynet: